site_name: Odoo Website Team Handbook
site_description: Shared knowledge for the Odoo Website team (dev, process, guides)
site_url: https://sergebayet.github.io/website-team-handbook/
repo_name: SergeBayet/website-team-handbook
repo_url: https://github.com/SergeBayet/website-team-handbook
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - content.code.copy
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - search.share
    - toc.integrate
  language: en
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - awesome-pages
  - git-revision-date-localized:
      enable_creation_date: true

nav:
  - Home: index.md
  - Development:
    - HTML Builder:
        - Introduction: dev/html_builder/index.md
        - Overview: dev/html_builder/overview.md
        - Architecture: dev/html_builder/architecture.md
        - Core Concepts: dev/html_builder/core-concepts.md
        - Structure Containers & COW: dev/html_builder/oe-structures.md
        - Builder Actions: dev/html_builder/builder-actions.md
        - Integration Points: dev/html_builder/integration.md
        - Key Components: dev/html_builder/key-components.md
        - Plugin Catalog: dev/html_builder/plugin-catalog.md
        - Migration Guide: dev/html_builder/migration.md
        - Examples: dev/html_builder/examples.md
        - Best Practices: dev/html_builder/best-practices.md
        - Troubleshooting: dev/html_builder/troubleshooting.md
        - Reference: dev/html_builder/reference.md
    - Website Editor Roles & Access: dev/website-editor-roles.md
  - Guides:
    - Debugging Cheatsheet: guides/debugging-cheatsheet.md
    - qsm-odoo Review Guidelines: guides/qsm-review-guidelines.md
  - Tutorials:
    - Create your own Builder Component: tutorials/create-your-own-builder-component.md
  - VoIP:
    - Commit History Report: voip/index.md
  - Reports:
    - Website & HTML Builder Commits (22–29 Oct 2025): reports/2025-10-29-odoo-website-html-builder-commits.md
    - Website & HTML Builder Commits (16–22 Oct 2025): reports/2025-10-22-odoo-website-html-builder-commits.md
    - Website & HTML Builder Commits (9–15 Oct 2025): reports/2025-10-15-odoo-website-html-builder-commits.md
    - Website & HTML Builder Commits (1–8 Oct 2025): reports/2025-10-08-odoo-website-html-builder-commits.md
    - Website & HTML Builder Commits (25 Sep–1 Oct 2025): reports/2025-10-01-odoo-website-html-builder-commits.md
    - Website & HTML Builder Commits (17–24 Sep 2025): reports/2025-09-24-odoo-website-html-builder-commits.md
